title: Fanz of Lena Zavaroni
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a fan made website and is not endorse by Lena Zavaroni's family or friends.

show_excerpts: false # set to true to show excerpts on the homepage or to false to hide excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%-d %B %Y"

# generate social links in footer
  social_links:
    # twitter: N/A
    github:  FanzOfLenaZavaroni
    rss: rss
    # dribbble: N/A
    # facebook: N/A
    # flickr:   N/A
    # instagram: N/A
    # linkedin: N/A
    # pinterest: N/A
    # youtube: FanzOfLenaZavaroni
    youtube_channel: UCTcpqllbI3ir8AlUT3RnO_g
    youtube_channel_name: Fanz of Lena Zavaroni
    # telegram: N/A
    # microdotblog: N/A

    # Mastodon instances
    # mastodon:
    # - username: N/A
    #   instance: example.com
    # - username: N/A
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
   - about & introduction.md
   - biographies.md
   - discography.md
   - onthisday.md
   - updates.md

collections_dir: my-collections
collections:
   albums:
      output: true
      permalink: /discography/albums/:name
   singles:
      output: true
      permalink: /discography/singles/:name
   collection3:
      output: true
      permalink: /:name 

include: ['biography']

# Build settings
markdown: kramdown
theme: minima

plugins:
 - jekyll-feed
 - jekyll-sitemap
 - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

