name: Manual Site Rebuild

on:
  workflow_dispatch:

jobs:
  trigger-builtin-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Built-In Page Builder
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://github.com{{ github.repository }}/pages/builds
